### ISSUE TITLE
The backup script fails when MONGODB_AUTH is not set

### ISSUE THREAD

**Issue by krzys-h** [dockhippie/mongodb#34]
My config is the following:
```
services:
  mongo:
    image: webhippie/mongodb:latest
    restart: always
    volumes:
     - ./data/db:/var/lib/mongodb
     - ./data/backup:/var/lib/backup
    environment:
     - MONGODB_SMALLFILES=1
     - MONGODB_OPLOG_SIZE=128
     - MONGODB_REPL_SET=rs0
     - MONGODB_STORAGE_ENGINE=wiredTiger
```
After upgrading the container recently (I needed a more modern version of MongoDB) the backup script no longer works. The problem seems to be related to [this line](https://github.com/dockhippie/mongodb/blob/master/latest/overlay/usr/bin/backup#L9):
```bash
if [[ -n "${MONGODB_AUTH}" ]]; then
```
it checks if `MONGODB_AUTH` is empty, but when it's not configured, the default value is `false`, not empty:
```
root@c62257dc78d8:/var/lib/mongodb# source /usr/bin/entrypoint
root@c62257dc78d8:/var/lib/mongodb# echo $MONGODB_AUTH
false
```
This causes it to call mongodump with `--authenticationDatabase admin`, which seems to fail on newer versions (or so I assume, because I don't see any changes to the backup script in the git log):
```
root@c62257dc78d8:/var/lib/mongodb# mongodump --authenticationDatabase admin --db=$DATABASE --out /tmp
2022-06-22T08:12:33.111+0000	Failed: can't create session: could not connect to server: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
root@c62257dc78d8:/var/lib/mongodb# mongodump --db=$DATABASE --out /tmp
... works normally ...
```
Suprisingly, this doesn't seem to be an issue when calling `mongo` to list the databases:
```
root@c62257dc78d8:/var/lib/mongodb# mongo --authenticationDatabase admin --eval 'JSON.stringify(db.adminCommand( { listDatabases: 1, nameOnly: true } ))'
MongoDB shell version v5.0.9
connecting to: mongodb://127.0.0.1:27017/?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("11430c48-3ec8-4605-b40c-f71e4fde031d") }
MongoDB server version: 5.0.9
{"databases":[...],"ok":1,"$clusterTime":{"clusterTime":{"$timestamp":{"t":1655885769,"i":1}},"signature":{"hash":{"$binary":"AAAAAAAAAAAAAAAAAAAAAAAAAAA=","$type":"00"},"keyId":{"$numberLong":"0"}}},"operationTime":{"$timestamp":{"t":1655885769,"i":1}}}
```
