### ISSUE TITLE
Connection error when creating/updating root user on container start up with --auth

### ISSUE THREAD

**Issue by lilian-pouliquen** [dockhippie/mongodb#53]
Hello,
I encountered the following error while using the `mongodb:5` image:
```
[...]

> update root user
Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):3:6
exception: connect failed
exiting with code 1
```

It seems to be only happening when the container is started with `docker-compose`. It works fine with a `docker run`. Here are my configs:
```
docker-compose.yaml
---
version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: ${IMAGE_MONGODB}
    env_file:
      - ./docker/mongodb.env
    restart: always
    networks:
      - mongodb_network
    volumes:
      - ${DATA_PATH}/mongodb/:/var/lib/mongodb/
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 32M

networks:
  mongodb_network:
    name: mongodb_network
    external: true
```

Note: `mongodb_network` is created with the following command: 
```
$ docker network create \
	--attachable \
	--driver bridge \
	--internal \
	--gateway 172.28.4.1 \
	--subnet 172.28.4.0/24 \
	mongodb_network
```
I though the error was due to the `--internal` but it occurs with or without it.

Here is the content of the `docker/mongodb.env` file:
```
mongodb.env
---
MONGODB_AUTH=true
MONGODB_AUTH_DB=authentication
MONGODB_ROOT_USERNAME=root
MONGODB_ROOT_PASSWORD=root
MONGODB_USERNAME=test
MONGODB_PASSWORD=test
MONGODB_DATABASE=testdb
MONGODB_PERFORM_UPGRADE=true
MONGODB_PERFORM_REPAIR=true
```

And finally the command which works: 
```
$ docker run \
    --detach \
    --volume $PWD/data/home-pouliquen/mongodb/:/var/lib/mongodb/ \
    --env-file docker/mongodb.env \
    --name mongodb \
    webhippie/mongodb:5
```

Th error occurs when the `MONGODB_AUTH=true` in the container script (l. 84-107).
I did not find anything to explain it, nor to correct it.
I hope you will be able to solve the issue with all these elements.

Thank you!

**Comment by lilian-pouliquen** [comment]
After further research, I found out that the container did not have enough memory allocated because of the following block of the  `docker-compose.yaml`:

```
deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 32M
```

I just gave it more memory and now it is running well.
Sorry about that.
